GET http://localhost:8080/api/v1/student/all
###
GET http://localhost:8080/api/v1/student/1/id
###
POST http://localhost:8080/api/v1/student
Content-Type: application/json

{
  "firstName": "Nikita",
  "lastName":  "Korshunov"
}
###
PUT http://localhost:8080/api/v1/student
Content-Type: application/json

{
  "id": 1,
  "firstName": "Alexander",
  "lastName":  "Korshunov"
}