version: '3'
services:
  db:

    image: mysql:8.0.23
    ports:
      - "3308:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
        - mysql-data:/var/lib/mysql

volumes:
  mysql-data: